- hosts: exchange_mailbox
  gather_facts: no
  vars:
    exchange_source_root: d:\
    exchange_disk_image_path: c:\exch\ExchangeServer2016-x64-cu3.iso
    exchange_org_name: testorg
  pre_tasks:
  - name: ensure Exchange media is available
    win_disk_image: 
      image_path: "{{ exchange_disk_image_path }}"
    register: diskimage_out
 
  - name: set source media var
    set_fact:
      exchange_source_root: "{{ diskimage_out.mount_path }}"
  roles:
  - exchange
